name: docs

on:
  push:
    branches:
    - master
  pull_request:
    types: [opened, synchronize, repoened, edited]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Setup Graphviz environment
      run: |
        sudo apt-get install graphviz

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
      
    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip # This path is specific to Ubuntu
        key: ${{ runner.os }}-pip-${{ hashFiles('./requirements/requirements.txt') }}-${{ hashFiles('**/docs.txt') }}-${{ hashFiles('**/test.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        pip install -r ./requirements/requirements.txt
        pip install -r ./requirements/docs.txt
        pip install -r ./requirements/test.txt

    - name: Run pydocstyle
      run: |
        pydocstyle pyreddit

    - name: Generate documentation
      run: |
        pdoc --html --output-dir="docs/" --template-dir="docs/templates" --config show_source_code=False --force .
      env:
        REDDIT_BOTS_MACHINE: GITHUB

    - name: Generate project dependency graphs
      run: |
        pyreverse --ignore="tests" -o png -p pyreddit pyreddit
        mkdir docs/pyreddit/images
        mv classes_pyreddit.png docs/pyreddit/images/classes_pyreddit.png
        mv packages_pyreddit.png docs/pyreddit/images/packages_pyreddit.png

    - name: Deploy docs to Github Pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: docs/pyreddit
